### PR TITLE
feat: drop support for PHP < 8.1

### PR DESCRIPTION
**Pull request by Chris53897**
migrate PHPUnit 9 => 11
improve PHPDocs
Flip arguments for test-asserts.
Use recommended tests functions.

I can not run tests, because of missing GitLab instance to test against.

### CODE REVIEW

**Comment by dandoetech** [comment]
@Chris53897  just came accross this PR while searching ... maybe this can help you to test gitlab with docker-compose:

(it's from my personal test-instance)

```yaml
  service-name-gitlab:
    # initial user will be: root
    # initial pass will be written in /etc/gitlab/initial_root_password

    # maybe you need to restart the container 1 or 2 times to get it running

    profiles:
      - test-gitlab
    image: gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: "
        external_url 'https://localhost';
        gitlab_rails['smtp_address'] = 'mailpit-or-mailhog-hostname';
        gitlab_rails['smtp_port'] = 1025;
        gitlab_rails['initial_root_password'] = 'password';
        gitlab_rails['display_initial_root_password'] = true;"
      # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "28443:443"
      - "28080:80"
      - "22022:22"
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
```

**Comment by Chris53897** [comment]
thanks @dolito 
I will try to find some time after my vaccation.
But i hope @RoyVoetman can help to verify this PR.

**Comment by RoyVoetman** [comment]
Sorry for the late reply, 

I will run the tests for this PR in the upcoming weekend.

**Comment by RoyVoetman** [comment]
Thanks for the work you put into this PR Chris, all works, I will merge this and tag a new release.

**Comment by RoyVoetman** [comment]
Merged into new version of package: https://github.com/RoyVoetman/flysystem-gitlab-storage/releases/tag/v3.1.0

**Comment by Chris53897** [comment]
Thanks

**Pull request merged**
