### PR TITLE
Reuse stream of HTTP request instead of create new stream

### PR DESCRIPTION
**Pull request by ElGigi**
Reuse stream of HTTP request instead of create new stream.

If you can test with your test environment ;).

### CODE REVIEW

**Comment by RoyVoetman** [comment]
It does not seem to work properly when reusing the guzzle stream 

```
1) GitlabAdapterTest::it_can_read_a_file_into_a_stream
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+'# Testing repo for `flysystem-gitlab`'

GitlabAdapterTest.php:81
```

**Comment by RoyVoetman** [comment]
Maybe a stream factory could be used: https://docs.guzzlephp.org/en/guzzle4/streams.html#creating-streams

**Comment by RoyVoetman** [comment]
Changed:
```
$this->assertEquals(stream_get_contents($stream, null, 0), $this->gitlabAdapter->read('README.md'));
```

To:
```
$this->assertEquals(stream_get_contents($stream), $this->gitlabAdapter->read('README.md'));
```

Results:
There was 1 failure:

1) GitlabAdapterTest::it_can_read_a_file_into_a_stream
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"file_name":"README.md","file_path":"README.md","size":37,"encoding":"base64","content_sha256":"e9492f2d51b0021ed15b97ecf8780ccd119f3628786de41aaff546aa126584d1","ref":"master","blob_id":"5762108fe413276c03951c653ac041c79e39c279","commit_id":"60324fe92d19b865684c7e5c59390fa32d0b13f8","last_commit_id":"ec1ac4fbb877266574474a7913f9f47ca548cfe1","content":"IyBUZXN0aW5nIHJlcG8gZm9yIGBmbHlzeXN0ZW0tZ2l0bGFiYA=="}'
+'# Testing repo for `flysystem-gitlab`'

GitlabAdapterTest.php:81

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.

**Comment by ElGigi** [comment]
Yes, my bad! JSON result... so not possible to reuse stream.

**Comment by ElGigi** [comment]
I read the API documentation; I hadn't seen the "../raw" route; so it works!

**Comment by RoyVoetman** [comment]
Nice! I should have known this, I even implemented a `readRaw` method in the client. Thanks for putting in the effort, I will add this in the new version when I have the time to test it in the testing environment.

**Pull request merged**
